apiVersion: apps/v1
kind: Deployment
metadata:
  name: sape-api
  labels:
    service.istio.io/canonical-name: ms-sape-backend
spec:
  selector:
    matchLabels:
      app: sape-api
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: sape-api
        service.istio.io/canonical-name: ms-sape-backend
        version: v1
        sidecar.istio.io/inject: {{ .Values.istio.enabled | quote }}
        istio.io/rev: {{ .Values.istio.rev | quote }}
        fluentd_logstash_prefix: backend-api-sape
      annotations:
        {{- if not .Values.override.enabled }}
        external-dns.alpha.kubernetes.io/internal-hostname: {{ tpl .Values.internalHost $ }}
        {{- end }}
        proxy.istio.io/config: {{ .Values.istio.proxy.config | toJson | squote }}
    spec:
      initContainers:
      - name: {{ .Chart.Name }}-migrate
        command:
        - npm
        - run
        - migrate
        image: {{ include "container-image" . }}
        imagePullPolicy: IfNotPresent
        env: {{- include "environment" . | indent 8 }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{ if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
        volumeMounts: {{- include "PKIVolumeMount" . | nindent 10 }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "container-image" . }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: /health-check
            port: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /health-check
            port: {{ .Values.port }}
        env: {{- include "environment" . | indent 8 }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{ if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
        volumeMounts: {{- include "PKIVolumeMount" . | nindent 10 }}
        {{- end }}

      {{ if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
      volumes: {{- include "PKIVolume" . | nindent 8 }}
      {{- end }}
