apiVersion: v1
kind: Service
metadata:
  name: {{ include "ms-fds.fullname" . }}
  labels:
    {{- include "ms-fds.labels" . | nindent 4 }}
    app: ms-fds
    service: ms-fds
    service.istio.io/canonical-name: ms-fds
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ms-fds.selectorLabels" . | nindent 4 }}
