apiVersion: v1
kind: Service
metadata:
  name: sape-api
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: http
  selector:
    app: sape-api
