{{- if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "postgresPKISecretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  path: "{{ tpl .Values.postgres.pki_secret.path $ }}"
  role: client
  secretEngine: pki
  engineOptions:
    common_name: "{{ include "postgresHost" $ }}"
    ttl: {{ .Values.postgres.pki_secret.ttl | quote }}
  type: Opaque
{{- end }}
