{{- if and .Values.postgres.pgoEnabled .Values.postgres.user_secret.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "postgresUserSecretName" . }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  path: {{ tpl .Values.postgres.user_secret.path $ }}
  role: {{ .Values.postgres.user_secret.role
           | default (printf "%s-%s-rw" (tpl .Values.postgres.name $) (tpl .Values.variables.PGDATABASE $)) }}
  secretEngine: database
  type: Opaque
{{- end }}
