{{- define "lifecycle-image" -}}
{{- with  .Values.lifecycle.image -}}
image: {{ tpl (printf "%s:%s" .repository .tag) $ | quote }}
{{- end }}
{{- end }}

{{- define "pki-volumes" -}}
{{- if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
volumeMounts: {{- include "PKIVolumeMount" . | nindent 0 }}
{{- end }}
{{- end }}

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ms-sape-backend
spec:
  entrypoint: run-command
  templates:
  - name: run-command
    metadata:
      labels:
        fluentd_logstash_prefix: backend-task-sape
    inputs:
      parameters:
        - name: command
    container:
      image: {{ include "container-image" . }}
      command:
      - 'bash'
      - '-c'
      - {{ "{{inputs.parameters.command}}; exit $?" | quote }}
      env: {{- include "environment" . | indent 6 }}
      {{- include "pki-volumes" . | nindent 6 }}
  - name: create-db
    metadata:
      labels:
        fluentd_logstash_prefix: backend-task-sape
    container:
      {{- include "lifecycle-image" $ | nindent 6 }}
      command:
      - "./main"
      - "create"
      env: {{- include "environment" . | indent 6 }}
      {{- include "pki-volumes" . | nindent 6 }}
  - name: create
    metadata:
      labels:
        fluentd_logstash_prefix: backend-task-sape
    steps:
    - - name: create-db
        template: create-db
    - - name: init-data
        template: run-command
        arguments:
          parameters:
          - name: command
            value: npm run init-data
  - name: delete
    metadata:
      labels:
        fluentd_logstash_prefix: backend-task-sape
    container:
      {{- include "lifecycle-image" $ | nindent 6 }}
      command:
      - "./main"
      - "delete"
      env: {{- include "environment" . | indent 6 }}
      {{- include "pki-volumes" . | nindent 6 }}
  nodeSelector: {{- toYaml .Values.workflows.nodeSelector | nindent 4 }}
  tolerations: {{- toYaml .Values.workflows.tolerations | nindent 4 }}
  {{- if and .Values.postgres.pgoEnabled .Values.postgres.pki_secret.enabled }}
  volumes: {{- include "PKIVolume" . | nindent 2 }}
  {{- end }}
