export const RAW_STROKE_MAX_WIDTH_IN_PROPORTION = 1 / 10;
export const FILL_MAX_WIDTH_IN_PROPORTION = 1 / 500;
export const HORIZONTAL_STROKE_MINIMAL_LENGTH = 1 / 10;
export const VERTICAL_STROKE_MINIMAL_LENGTH = 1 / 10;
