{{- define "minio_secret" }}

apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .minioSecretName | default "argo-workflow-minio-access" }}
  namespace: {{ .Release.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  keys:
  - storageaccountname
  - storageaccountkey
  templates:
    accesskey: "{% .Secrets.storageaccountname %}"
    secretkey: "{% .Secrets.storageaccountkey %}"
  path: {{ .minioSecretPath }}
  type: Opaque

{{- end }}
