{{/*
    Args:
      secrets (required)  -> dictionnary of secrets to use
      Values (required)   -> All the values

    You can debug the return of get_secrets by appending this:

    raw:
      {{- include "get_secrets" $ | fromJson | toYaml | nindent 4 }}
*/}}
{{- define "vault-secret" }}
{{- $secrets := include "get_secrets" . | fromJson }}
{{- range $key, $value := $secrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $key }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  {{- toYaml $value | nindent 2 }}
  type: Opaque
{{- end }}
{{- end }}
